#!/bin/sh

REL="$(dirname "$0")"
ABS="$(cd "$REL"; pwd)"

BGA="$REL/bootstrap/gambit"
GAM="$REL/gambit"
GSC="$REL/gambit/bin/gsc"
SCM="$REL/kernel/jam.scm"

bootstrap_init () {
	cd "$REL"
    git submodule init
}

bootstrap_update () {
	cd "$REL"
    git submodule update
}

bootstrap_configure () {
	PREFIX="$ABS/gambit"
    cd "$BGA" &&
    ./configure --prefix="$PREFIX" $(host)
}

bootstrap_make () {
    ( [ -f "$BGA/config.status" ] || bootstrap_configure ) &&
    cd "$BGA" &&
    make -j $(jobs)
}

bootstrap_install () {
    cd "$BGA" &&
    make install
}

bootstrap () {
    (bootstrap_init) &&
    (bootstrap_update) &&
    (bootstrap_make) &&
    (bootstrap_install)
}

bootstrap_dispatch () {
    case "$1" in
    
	"init" )
	    bootstrap_init
	    ;;
	"update" )
	    bootstrap_update
	    ;;
	"configure" )
	    bootstrap_configure
	    ;;
	"make" )
	    bootstrap_make
	    ;;
	"install" )
	    bootstrap_install
	    ;;
	"" )
	    bootstrap
	    ;;
	* )
	    echo "Unknown bootstrap option : $1"
	    return 1
	    ;;
	
    esac
}

jobs () {
    [ -n "${JAZZ_JOBS:+x}" ] && echo "$JAZZ_JOBS" || echo 1
}

host () {
    if [ ! -n "${JAZZ_MULTIHOST:+x}" ] || [ "$JAZZ_MULTIHOST" == "0" ]; then
		echo "--enable-single-host"
    fi
}

if [ "x$1" == "xbootstrap" ]; then
	bootstrap_dispatch $2
	exit
fi

if [ ! -f "$GSC" ]; then
	bootstrap_dispatch
fi

if [ ! -f "$GSC" ]; then
	echo "Unable to find ./gambit/bin/gsc."
	exit 1
fi

exec "$GSC" -:="$GAM" -i "$SCM" "$@"
