#!/bin/sh

REL="$(dirname "$0")"
ABS="$(cd "$REL"; pwd)"

if [ -f ".jaz" ]; then
    . "$(pwd)/.jaz"
fi

GSC="$GAMBITDIR/bin/gsc"
SCM="$REL/kernel/jaz.scm"

display_module_info () {
    echo "$1"
    if [ -d "$2" ]; then
        cd "$2" &&
        git log -1
    fi
}

display_info () {
    (display_module_info "Jazz" "$REL")
}

case "$1" in
    "info" )
        display_info
        exit
        ;;

    "environment" )
        echo "REL: $REL"
        echo "ABS: $ABS"
        echo "GAMBITDIR: $GAMBITDIR"
        echo "GSC: $GSC"
        echo "SCM: $SCM"
        exit
        ;;
esac

if [ ! -f "$GSC" ]; then
    echo "Unable to find $GAMBITDIR/bin/gsc"
    exit 1
fi

exec "$GSC" -:="$GAMBITDIR" -i "$SCM" "$@"
