#!/bin/sh

if [ -n "${GSC_JAZZ:+x}" ]; then
	GSC=$GSC_JAZZ
	GSC_JAZZ_SET=true
elif [[ $(uname) == *MINGW* ]]; then
	GSC=gsc
	GSC_JAZZ_SET=false
else
	GSC=gsc-script
	GSC_JAZZ_SET=false
fi

if ! type -p $GSC &> /dev/null ; then
	if $GSC_JAZZ_SET; then
		echo "Gambit-Jazz compiler $GSC which is set in GSC_JAZZ is non-existant"
	else
		echo "Gambit-Jazz compiler $GSC cannot be found in the PATH"
	fi
	
	exit 1
fi

exec $GSC "$@"