#!/bin/sh

bootstrap_init () {
    git submodule init
}

bootstrap_update () {
    git submodule update
}

bootstrap_configure () {
    PREFIX=$(pwd)/gambit
    cd bootstrap/gambit &&
    ./configure --prefix=$PREFIX --enable-single-host
}

bootstrap_make () {
    ( [ -f bootstrap/gambit/config.status ] || bootstrap_configure ) &&
    cd bootstrap/gambit &&
    make -j2
}

bootstrap_install () {
    cd bootstrap/gambit &&
    make install
}

bootstrap () {
    (bootstrap_init) &&
    (bootstrap_update) &&
    (bootstrap_make) &&
    (bootstrap_install)
}

if [ "$1" = init ]; then
    bootstrap_init &&
    exit 0 || exit 1
fi

if [ "$1" = update ]; then
    bootstrap_update &&
    exit 0 || exit 1
fi

if [ "$1" = configure ]; then
    bootstrap_configure &&
    exit 0 || exit 1
fi

if [ "$1" = make ]; then
    bootstrap_make &&
    exit 0 || exit 1
fi

if [ "$1" = install ]; then
    bootstrap_install &&
    exit 0 || exit 1
fi

bootstrap &&
exit 0 || exit 1
