#!/bin/sh

if [ "$1" = init ]; then
	PREFIX=$(PWD)/gambit-c
	[ -d gambit-c ] && rm -rf gambit-c
	mkdir gambit-c &&
	cd gambit-c &&
	git clone http://10.1.1.25/gambit-dist src &&
	cd src &&
	./configure --prefix=$PREFIX --enable-single-host &&
	make -j2 distribution &&
	make install-distribution &&
	exit 0 || exit 1
fi

if [ "$1" = update ]; then
	cd gambit-c/src &&
	git pull &&
	make -j2 distribution &&
	make install-distribution &&
	exit 0 || exit 1
fi
	
if [ -n "${GSC_JAZZ:+x}" ]; then
	if [ -f $GSC_JAZZ ]; then
		exec $GSC_JAZZ "$@"
	else
		echo "Gambit-Jazz compiler $GSC_JAZZ which is set in GSC_JAZZ is non-existant"
		exit 1
	fi
fi

[ -f gambit-c/bin/gsc ] && exec gambit-c/bin/gsc "$@"

echo "GSC_JAZZ not set and local Gambit-Jazz not initialized. Fallback on system gambit-c. Run jbs init to setup local Gambit-Jazz\n"

if [[ $(uname) == *MINGW* ]]; then
	GSC=gsc
else
	GSC=gsc-script
fi

if ! type -p $GSC &> /dev/null ; then
	echo "Gambit-c compiler $GSC cannot be found in PATH"
	exit 1
fi

exec $GSC "$@"